### ISSUE TITLE
Crawler Update

### ISSUE THREAD

**Issue by sauravhiremath** [sauravhiremath/fifa-stats-crawler#1]
New data to be collected
- [x] Player Id
- [x] Player Short names
- [x] Most played player position
- [x] Club and country logo URLs

Old Data to be fixed
 - [x] TBD

**Comment by trivius86** [comment]
Hi, congratulations on the code! Crazy! But there is a value that seems small but for some it is very important in DB.
I'm talking about the ID code of the footballers that everyone has their constant. Is it possible to extract it?

**Comment by sauravhiremath** [comment]
Yeah @trivius86, that does seem to have a legit use case. Adding the param to the above list :rocket:

**Comment by Akram9** [comment]
Hi! I would like to work on making this crawler.

**Comment by sauravhiremath** [comment]
Yeah sure, Akram go ahead :+1: 

To get started you can:

- Add selectors for new keys which are discussed above
- Check if any existing one has changed (most probably it wouldn't have, but a confirmation would be great)

**Comment by Akram9** [comment]
Thank you. I shall start tomorrow with this.

**Comment by Akram9** [comment]
Hi Saurav.<br>
I ran the spiders and the `players_url` is running fine and turning its contents to the `players_stats.json` file.<br>
But the `players_stats` crawler needs the `players_url.json`. I think it is the same as `players_stats.json` file. And infact, running it by making this change works fine.<br><br>
Am I doing it right, or missing something?
<br><br>
By the way, I didn't do much today. Just read up the Scrapy docs and tried the spiders. I added the selector for `id`. I will have to do the same for other keys.<br>
Anyway, I didn't get your second point - `Check if any existing one has changed (most probably it wouldn't have, but a confirmation would be great)`.<br>
Do you mean that the site has changed its format? It does not seem so when I ran the spiders, but didn't give a thorough look.

**Comment by sauravhiremath** [comment]
Yeah @Akram9 that is correct.

Right now, you need to manually change the output file name. Making it a two-step thing.
There will be another PR to make this process smoother.
Feel free to create an issue for this, if needed. I will look into it

And don't worry about the pace, you doing good!

Answering your last question, yes you are right. I meant checking the site for any change in format. There might be missing keys under rare cases, so it might be hard to find. Just for the sake of this PR, if the result looks fine for a few cases, we can proceed further. Any, specific changes if noticed can be incorporated later on as a fix

**Comment by Akram9** [comment]
Hey Saurav,

I tried adding the remaining keys selectors, but am facing probelms.

Regarding the last one - country and club logo urls, some players like https://sofifa.com/player/254247?units=mks have only country logo while others like https://sofifa.com/player/240963?units=mks have only club logo url while some like Messi have both. But there does not seem to be any way in the html to differentiate. What should I do here?

Also I did not get any player short names or most played position in the website of any player. Only that there is a position tag, for which a selector has already been added to the spider.

**Comment by sauravhiremath** [comment]
Hi @Akram9 ,

## The most played position (can rename this to primary-position), is found on the **left bottom of the webpage.**
 
  **Checked For**: https://sofifa.com/player/240963?units=mks
  
  **Selector**: `#list > div:nth-child(5) > div > div > div.column.col-4 > div:nth-child(2) > ul > li:nth-child(1) > label`
  
![image](https://user-images.githubusercontent.com/28642011/95262932-adb73800-084a-11eb-9ffc-d03d406d3804.png)

## Regarding the first update, it does show me both the club logo URL and country flag URL for each of both links you mentioned.

![image](https://user-images.githubusercontent.com/28642011/95263865-13f08a80-084c-11eb-8b16-a3d002353767.png)

![image](https://user-images.githubusercontent.com/28642011/95263928-28cd1e00-084c-11eb-933c-a636809a761c.png)

  Maybe I misunderstood something here?

**Comment by Akram9** [comment]
Okay I got it. No, it was me who misunderstood. I was confusing country flag with country-club logo, like Egypt in the first case.

Thanks for your help. I will get the selectors ready.

Also, do I add the club logo urls as a list, or do I make a dictionary of club names vs urls? Because some like Messi have multiple clubs.

Edit - this is how I have made the output - ```'player_country_logo_url': 'https://cdn.sofifa.com/flags/ar.png', 'player_club_logos_urls': {'FC Barcelona': 'https://cdn.sofifa.com/teams/241/light_60.png', 'Argentina': 'https://cdn.sofifa.com/teams/1369/light_60.png'}}```

**Comment by sauravhiremath** [comment]
Sorry for the delayed response, but yeah this works!

You can make them nested so, the naming convention becomes more clear

```javascript
logo: {
  country: {
    name: 'Argentina',
    url: 'https://cdn.sofifa.com/flags/ar.png'
  },
  club: {
    name: 'FC Barcelona',
    url: 'https://cdn.sofifa.com/teams/241/light_60.png'
  },
  nationalClub: {
    name: 'Argentina', // You can keep this same as country.name
    url: 'https://cdn.sofifa.com/teams/1369/light_60.png'
  }
}
```

If the player has a `nationalClub` you can add that entry, or omit it. Also, I don't think any player should have more than 2 clubs (league club and country club). So, this should be good to go. Lemme know what u think

Other than that, this looks great!

**Comment by Akram9** [comment]
Sorry, even I have been very busy.

I have already thought of this style of output you are suggesting.

I should be done making the remaining changes to the crawler by tomorrow.

Yes, I didn't find any player with more than two clubs. But I think I will be able handle them even if there are any more.

I'll get back to you tomorrow.

**Comment by Akram9** [comment]
Hi Saurav,

I am done with all the selectors except the short name selector.

Is the short name the name at the top of the page like L. Messi?

If it is, then should I take the whole short name or just the last name?

*Edit -*

I have added the short name in the info part, this way - 
```
{
    'name': 'Lionel Andrés Messi Cuccittini', 
    'short_name': 'L. Messi', 
    'id': '158023', 
    'photo_url': 'https://cdn.sofifa.com/players/158/023/21_120.png',
    ...
}
```
Is this fine?

**Comment by sauravhiremath** [comment]
@Akram9 

> ```
> {
>     'name': 'Lionel Andrés Messi Cuccittini', 
>     'short_name': 'L. Messi', 
>     'id': '158023', 
>     'photo_url': 'https://cdn.sofifa.com/players/158/023/21_120.png',
>     ...
> }
> ```
> 
> Is this fine?

Yeah, this looks fine. 

As you mentioned, let's keep the whole short-name, it would help in better indexing. The reason for this is: some players are popularly known by their short-names and not their original ones (Ex. Issco, you may search for his real name if you curious :grin: )

Edit: `Francisco Román Alarcón Suárez` is the real name for `Isco`. As we can see, users searching for `Isco`, won't be a hit in the DB unless we add the short-name

**Comment by Akram9** [comment]
> Francisco Román Alarcón Suárez is the real name for Isco. As we can see, users searching for Isco, won't be a hit in the DB unless we add the short-name

Okay, yeah, that makes sense.

Perhaps then you can check the whole output for Isco for example - 

```
{
    'name': 'Francisco Román Alarcón Suárez', 
    'short_name': 'Isco', 
    'id': '197781', 
    'photo_url': 'https://cdn.sofifa.com/players/197/781/21_120.png', 
    'positions': 'CAM,CM,LW', 
    'age': '28', 
    'birth_date': '1992/Apr/21', 
    'height': 176, 
    'weight': 79, 
    'Overall Rating': 84, 
    'Potential': 84, 
    'Value': '€31.5M', 
    'Wage': '€210K', 
    'Preferred Foot': 'Right', 
    'Weak Foot': 3, 
    'Skill Moves': 4, 
    'International Reputation': 3, 
    'Work Rate': 'Medium/ Low', 
    'Body Type': 'Normal (170-185)', 
    'Real Face': 'Yes', 
    'Release Clause': '€64.6M', 
    'teams': {'Real Madrid': 85}, 
    'attacking': {'Crossing': 78, 'Finishing': 76, 'HeadingAccuracy': 55, 'ShortPassing': 84, 'Volleys': 67}, 
    'skill': {'Dribbling': 92, 'Curve': 88, 'FKAccuracy': 76, 'LongPassing': 81, 'BallControl': 91}, 
    'movement': {'Acceleration': 71, 'SprintSpeed': 65, 'Agility': 83, 'Reactions': 74, 'Balance': 90}, 
    'power': {'ShotPower': 69, 'Jumping': 61, 'Stamina': 61, 'Strength': 59, 'LongShots': 81}, 
    'mentality': {'Aggression': 58, 'Interceptions': 61, 'Positioning': 76, 'Vision': 83, 'Penalties': 76, 'Composure': 85}, 
    'defending': {'DefensiveAwareness': 58, 'StandingTackle': 64, 'SlidingTackle': 51}, 
    'goalkeeping': {'GKDiving': 10, 'GKHandling': 8, 'GKKicking': 12, 'GKPositioning': 15, 'GKReflexes': 6}, 
    'player_traits': 'Finesse Shot,Flair,Playmaker (AI),Outside Foot Shot,Technical Dribbler (AI)', 
    'player_hashtags': '#Dribbler', 
    'logos': {
        'country': {'name': 'Spain', 'url': 'https://cdn.sofifa.com/flags/es.png'}, 
        'club': {'name': 'Real Madrid', 'url': 'https://cdn.sofifa.com/teams/243/light_60.png'}
    }, 
    'most_played_position': 'CAM'
}
```

**Comment by sauravhiremath** [comment]
This looks good. Just some suggestions

1. Rename `most_played_position` to `primary_position`
2. Split the `positions` string (`CAM,CM,LW`) to a list (`['CAM', 'CM', 'LW']`). The same thing with `player_hashtags` and `player_traits`

**Comment by Akram9** [comment]
Seems I am done - Messi example - 

```
{
    'name': 'Lionel Andrés Messi Cuccittini',
    'short_name': 'L. Messi', 
    'id': '158023', 
    'photo_url': 'https://cdn.sofifa.com/players/158/023/21_120.png', 
    'positions': ['RW', 'ST', 'CF'], 
    'age': '33', 
    'birth_date': '1987/Jun/24', 
    'height': 170, 
    'weight': 72, 
    'Overall Rating': 93, 
    'Potential': 93, 
    'Value': '€67.5M', 
    'Wage': '€560K', 
    'Preferred Foot': 'Left', 
    'Weak Foot': 4, 
    'Skill Moves': 4, 
    'International Reputation': 5, 
    'Work Rate': 'Medium/ Low', 
    'Body Type': 'Messi', 
    'Real Face': 'Yes', 
    'Release Clause': '€138.4M', 
    'teams': {'FC Barcelona': 84, 'Argentina': 83}, 
    'attacking': {'Crossing': 85, 'Finishing': 95, 'HeadingAccuracy': 70, 'ShortPassing': 91, 'Volleys': 88}, 
    'skill': {'Dribbling': 96, 'Curve': 93, 'FKAccuracy': 94, 'LongPassing': 91, 'BallControl': 96}, 
    'movement': {'Acceleration': 91, 'SprintSpeed': 80, 'Agility': 91, 'Reactions': 94, 'Balance': 95}, 
    'power': {'ShotPower': 86, 'Jumping': 68, 'Stamina': 72, 'Strength': 69, 'LongShots': 94}, 
    'mentality': {'Aggression': 44, 'Interceptions': 40, 'Positioning': 93, 'Vision': 95, 'Penalties': 75, 'Composure': 96}, 
    'defending': {'DefensiveAwareness': 32, 'StandingTackle': 35, 'SlidingTackle': 24}, 
    'goalkeeping': {'GKDiving': 6, 'GKHandling': 11, 'GKKicking': 15, 'GKPositioning': 14, 'GKReflexes': 8}, 
    'player_traits': ['Finesse Shot', 'Long Shot Taker (AI)', 'Speed Dribbler (AI)', 'Playmaker (AI)', 'Outside Foot Shot', 'One Club 
        Player', 'Team Player', 'Chip Shot (AI)'], 
    'player_hashtags': ['#Dribbler', '#Distance Shooter', '#FK Specialist', '#Acrobat', '#Clinical Finisher', '#Complete Forward'], 
    'logos': {
        'country': {'name': 'Argentina', 'url': 'https://cdn.sofifa.com/flags/ar.png'}, 
        'club': {'name': 'FC Barcelona', 'url': 'https://cdn.sofifa.com/teams/241/light_60.png'}, 
        'nationalClub': {'name': 'Argentina', 'url': 'https://cdn.sofifa.com/teams/1369/light_60.png'}
    }, 
    'primary_position': 'RW'
}
```

**Comment by sauravhiremath** [comment]
This is good to go! Solid work :+1:

**Comment by Akram9** [comment]
Okay then, shall I submit a PR?

**Comment by sauravhiremath** [comment]
> Okay then, shall I submit a PR?

Sure go ahead
