### ISSUE TITLE
[revised] Scrapy Playes Stats not working

### ISSUE THREAD

**Issue by FVitor7** [sauravhiremath/fifa-stats-crawler#8]
not scrapy playes stats

**Comment by sauravhiremath** [comment]
Hey @FVitor7 , thanks for reporting this!

It seems they have updated their site layout, pushing a fix for this :D

**Comment by sauravhiremath** [comment]
@FVitor7 Fixed in 81f6f40439b6617f5c31853c00b71dac98eef0bd. Could you confirm if you facing the same issue yet?

Also, updated the docs, so its easier to run now

**Comment by FVitor7** [comment]
Yes, it's working perfectly ... Thank you very much

**Comment by FVitor7** [comment]
I will do with the sofifa the same as I did with Pesmaster.

I have a project on my github where I extract the Pes2021 player data from the pesmaster website and added it to an SQL. After that build a backend + frontend application that allows me to search for players in the database by name, nationality and team and displays the skills of the players converted to the old Pes6. Soon I will do the same with the sofifa, adapting to the old Pes6.

Your application will help me a lot with this!

I'll leave the link to my project if you want to see: https://github.com/FVitor7/PyMaster-Pes2021-stats-to-PES6

and the application working: https://pesmaster.herokuapp.com/

**Comment by sauravhiremath** [comment]
Sounds like a promising project! Good luck for the project :smile:
